### ISSUE TITLE
Station to Station list missing W and Z lines

### ISSUE THREAD

**Issue by kaushik12** [tsdataclinic/mta#6]
**Describe the issue**
Station to Station connections doesn't seem to include the W and Z line stops. I think this is because both of these lines don't have any unique stop IDs and share it with other lines.

**Comment by MatthewMaclean** [comment]
We don't have data for the W or the Z train in the stop_times.txt, that's the issue. Where did we get that data / how do we refresh it?

**Comment by kaushik12** [comment]
@MatthewMaclean `stop_times.txt` comes from MTA's static GTFS feed. I looked into it and found the issue. The `trip_id` for these two lines are different and refer to N and J in there. What we have to do is merge `stop_times.txt` with `trips.txt` to get the correct `route_id`. That should resolve the issue.

**Comment by MatthewMaclean** [comment]
Fixed now
